M48
; DRILL file KiCad 10.0.3-10.0.3~ubuntu26.04.1 date 2026-06-21T13:42:23
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-21T13:42:23-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3-10.0.3~ubuntu26.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X30.0Y-27.0
X30.0Y-66.5
X105.0Y-27.0
X105.0Y-66.5
M30
